### ISSUE TITLE
Confusion around »Characteristics of good "Consequences" section in an ADR«

### ISSUE THREAD

**Issue by Philzen** [joelparkerhenderson/architecture-decision-record#52]
All of the advice in the [suggestions for writing good ADRs](https://github.com/joelparkerhenderson/architecture-decision-record#suggestions-for-writing-good-adrs) are pretty well laid out and helpful (thank you for that btw), but i get confused about the following passage:

    Characteristics of good "Consequences" section in an ADR:

    *  Right approach - "We need to start doing X instead of Y"
    *  Wrong approach - Do not explain the AD in terms of "Pros" and "Cons" of having made the particular AD

So is the "wrong approach" *not* explaining pros & cons (meaning they *have to be* there?  
Is the wrong approach of pros & cons just to mention them in context of the *particular AD* that has been arrived at, meaning they can be listed, but should remain non-opinionated in the context of the decision drivers?
Is the wrong approach to explain why it is good having made the concerned AD at all? (this is my best guess, but i couldn't think of any cons of having made and documented an AD)
Or does it actually mean that listing pros/cons is discouraged?

If the latter applies, i'm specifically confused because [MADR](https://github.com/joelparkerhenderson/architecture-decision-record/blob/main/templates/decision-record-template-madr/index.md) listing positive (pros) and negative consequences (cons) as part of their template (actually as sub-sections of the decision that was arrived at).

Can you kindly shed some light on this and clarifiy?

Maybe it would help to rewrite this section in-line with the other ones above this passage, b/c all of them just list what should be there, rather than what shouldn't. Having a "do not" section *may* be helpful, but only if it follows good advice on what the consequences section *should* contain. I guess the "Right approach / wrong approach"-prefix is part of my confusion and could be dropped, in terms of harmonizing it with the way the first paragraph (Characteristics of a good ADR) is written.

I hope my question makes any sense :wink:

**Comment by joelparkerhenderson** [comment]
Yes your question makes sense. How's this rewrite?

###

Characteristics of good "Consequences" section in an ADR:

  * Explain what follows from making the decision. This can include the effects, outcomes, outputs, follow ups, and more.

  * Include information about any subsequent ADRs. It's relatively common for one ADR to trigger the need for more ADRs, such as when one ADR makes a big overarching choice, which in turn creates needs for more smaller decisions.

  * Include any after-action review processes. It's typical for teams to review each ADR one month later, to compare the ADR information with what's happened in actual practice, in order to learn and grow.

**Comment by Philzen** [comment]
Sounds lovely, everything in this rewrite makes perfect sense to me :heart: 

Absolutely no confusion here.

When i read though the examples, they don't have a "Consequences" section, but do list [**implications**](https://github.com/joelparkerhenderson/architecture-decision-record/blob/main/examples/environment-variable-configuration/index.md#implications) – things that need to be sorted out as a *consequence* of the decision.

So my only suggestion could be to add the word "implications" (either next to "Consequences" or in the first bullet point), but in generally i think your rewrite makes a great improvement.

Thanks for your quick response!

**Comment by Philzen** [comment]
(keeping this open just in case you want to track the change commit to-do)

**Comment by Philzen** [comment]
Even though it doesn't say anything on implications, i can see 28be671b59b28f7aec1ee8a8fec026ee07757b92 added your suggested improvements, hence closing this issue.

Thanks :+1:
