### ISSUE TITLE
Typo:  "Rational" instead of "Rationale"

### ISSUE THREAD

**Issue by jrobbins-LiveData** [joelparkerhenderson/architecture-decision-record#61]
In https://github.com/joelparkerhenderson/architecture-decision-record/blob/33c7393ca875df3e9f06221f6b568e5dd6162b28/README.md?plain=1#L192 I believe the first word was meant to be `Rationale`, not `Rational`.

**Comment by joelparkerhenderson** [comment]
Good catch! Yes you're correct. I'm fixing it now. Thanks!
