### ISSUE TITLE
May I Translate This GitHub Repository into Korean?

### ISSUE THREAD

**Issue by parkchanjong** [joelparkerhenderson/architecture-decision-record#68]
Hello,

I would like to inquire about the possibility of translating the content of this GitHub repository into Korean. I'm seeking to know if there are any specific permissions or guidelines for initiating such a translation. Before commencing the translation work, I would appreciate your guidance on any necessary permissions or discussions.

I believe that your input or approval may be required before I proceed with the translation work. Your cooperation and guidance would be greatly appreciated.

Thank you!

**Comment by joelparkerhenderson** [comment]
Great question! Yes. The work is already in progress in issue #66 . Can you read that and let me know how you would like to proceed? Thanks!
